export const COPY = {
  landing: {
    title: '잠깐명상',
    startAriaLabel: '잠깐명상 시작하기',
    instructionLines: ['화면을 터치해', '모래시계를 뒤집어보세요.'],
    supportingLines: ['휴대폰을 내려놓고', '잠깐 주변을 바라봐요.'],
    longSession: (duration: string) => `${duration} 동안 머물러요.`,
  },
  pause: {
    initialLines: ['휴대폰을 내려놓고', '잠깐 주변을 바라봐요.'],
    milestoneTitle: (duration: string) =>
      `${duration}${duration.endsWith('초') ? '가' : '이'} 지났어요.`,
    milestoneBodyLines: ['더 머물고 싶다면', '그대로 있어도 괜찮아요.'],
    milestoneActionLines: ['돌아오고 싶을 때', '화면을 눌러주세요.'],
  },
  reflection: {
    question: '눈에 들어온 것은 무엇이었나요?',
    keywordPlaceholder: '예: 구름',
    noteLabel: '조금 더 남기고 싶다면',
    notePlaceholder: '생각보다 하늘이 빠르게 움직이고 있었다.',
    placeLabel: '장소',
    placeAction: '+ 장소 남기기',
    placePlaceholder: '예: 석촌호수',
    validationKeyword: '짧게 하나만 남겨주세요.',
    submit: '기록 남기기',
  },
  result: {
    title: '잠깐, 멈춘 기록',
    duration: (duration: string) => `${duration} 머물렀어요.`,
    place: (place: string) => `${place}에서`,
    share: '공유하기',
    download: '이미지로 저장하기',
    preparingShare: '공유 준비 중...',
    preparingImage: '이미지 만드는 중...',
    shareUnavailable: '이미지로 저장해 직접 공유할 수 있어요.',
    shareError: '공유하지 못했어요. 이미지로 저장해 직접 공유할 수 있어요.',
    imageError: '이미지를 만들지 못했어요. 다시 한 번 시도해주세요.',
    privacy: '이 기록은 이곳에 저장되지 않아요.',
    saveHint: '공유 메뉴에서 이미지를 저장할 수도 있어요.',
    downloadHint: '남겨두고 싶다면 이미지로 가져가세요.',
    restart: '처음으로',
  },
  time: {
    hours: (value: number) => `${value}시간`,
    minutes: (value: number) => `${value}분`,
    seconds: (value: number) => `${value}초`,
  },
} as const
